# Generated by Django 5.1.1 on 2024-09-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  #type: ignore
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados unidos'), ('BRAZIL', 'Brasil'), ('UK', 'Reino Unido')], max_length=100, null=True)),
            ],
        ),
    ]
